# Generated by Django 4.2.23 on 2025-09-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='thumbnail_media',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
