# Generated by Django 4.2.24 on 2025-09-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_tareas_thumbnail_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('terapeutica', 'Terapéutica'), ('administrativa', 'Administrativa'), ('financiera', 'Financiera')], max_length=20, verbose_name='Área')),
                ('asunto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
    ]
