# Generated by Django 4.2.24 on 2026-07-02 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_profile_celular_alter_profile_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTerapeutaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_terapia', models.CharField(default='General', max_length=100, verbose_name='Especialidad')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.profile')),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil_terapeuta')),
            ],
            options={
                'unique_together': {('paciente', 'terapeuta', 'tipo_terapia')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='terapeutas',
            field=models.ManyToManyField(related_name='pacientes_asignados', through='usuarios.AsignacionTerapeutaPaciente', to='usuarios.perfil_terapeuta', verbose_name='Cuerpo Terapéutico Asignado'),
        ),
    ]
