# Generated by Django 4.2.20 on 2025-04-14 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0003_alter_profile_options_profile_asunto_profile_cuerpo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='asunto',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cuerpo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emisor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fecha_envio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='leido',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='receptor',
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(blank=True, max_length=255, null=True)),
                ('cuerpo', models.TextField(blank=True, null=True)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
