# Generated by Django 4.2.20 on 2025-07-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_tareas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='actividad_realizada',
            field=models.BooleanField(default=False, verbose_name='¿Realizó la terea?'),
        ),
    ]
