# Generated by Django 4.2.24 on 2025-09-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='adjuntos_contacto/'),
        ),
    ]
