# Generated by Django 4.2.23 on 2025-08-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_perfilinstitucional_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionterapia',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.prospeccion', verbose_name='Institución'),
        ),
    ]
