# Generated by Django 4.2.20 on 2025-07-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_tareas_actividad_realizada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareacomentario',
            options={'ordering': ['fecha'], 'verbose_name': 'Revisar Tarea Terapeutica', 'verbose_name_plural': 'Tareas Terapeuticas'},
        ),
    ]
