# Generated by Django 4.2.24 on 2025-09-29 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_contacto_adjunto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Contactos de usuarios', 'verbose_name_plural': 'Contactos de usuarios'},
        ),
        migrations.AddField(
            model_name='contacto',
            name='emisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacto_paciente', to='usuarios.profile', verbose_name='Administrador emisor'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal0', to='usuarios.sucursal'),
        ),
    ]
