# Generated by Django 4.2.20 on 2025-07-30 01:51

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_profile_certificado_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_terapeuta',
            name='pago_por_hora_institucional_a_domicilio',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=10, null=True, verbose_name='Pago por hora institucional a domicilio'),
        ),
    ]
