# Generated by Django 4.2.20 on 2025-04-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(choices=[('Consulta', 'Consulta'), ('Sugerencia', 'Sugerencia'), ('Informativo', 'Informativo'), ('Terapéutico', 'Terapéutico'), ('Solicitud de pago vencido', 'Solicitud de pago vencido'), ('Solicitud de Certificado Médico', 'Solicitud de Certificado Médico'), ('Reclamo del servicio  Médico', 'Reclamo del servicio  Médico'), ('Cancelación del servicio Médico', 'Cancelación del servicio Médico')], default='Consulta', max_length=50),
        ),
    ]
