# Generated by Django 4.2.23 on 2025-08-26 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_valoracionterapia_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informesterapeuticos',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='usuarios.valoracionterapia', verbose_name='Informe Terapéutico'),
        ),
    ]
