# Generated by Django 4.2.20 on 2025-07-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_tareacomentario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='fecha_actividad',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actividad'),
        ),
    ]
