# Generated by Django 4.2.24 on 2025-10-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_contacto_options_contacto_emisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
