# Generated by Django 4.2.24 on 2025-10-15 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_tareas_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='es_en_convenio',
            field=models.BooleanField(default=False, verbose_name='Convenio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=120, null=True, verbose_name='Sexo del Paciente'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='media_terapia',
            field=models.FileField(blank=True, upload_to='Videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Video Multimedia de actividad'),
        ),
    ]
