# Generated by Django 4.2.20 on 2025-07-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_perfil_terapeuta_pago_por_hora_institucional_a_domicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='area',
            field=models.CharField(blank=True, choices=[('psicologia', 'Psicología'), ('terapia_lenguaje', 'Terapia de Lenguaje'), ('ocupacional', 'Terapia Ocupacional')], max_length=50, null=True, verbose_name='Área Terapéutica'),
        ),
    ]
