# Generated by Django 4.2.20 on 2025-07-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_tareas_fecha_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='tipo_cita',
            field=models.CharField(blank=True, choices=[('administrativa', 'Administrativa'), ('terapeutica', 'Terapéutica'), ('particular', 'Particular'), ('urgente', 'Urgente')], default='terapeutica', max_length=20, null=True, verbose_name='Categoría de Cita'),
        ),
    ]
