# Generated by Django 4.2.23 on 2025-08-27 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0006_alter_informesterapeuticos_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informesterapeuticos',
            options={'ordering': ['-fecha_creado'], 'verbose_name': 'Informe Terapéutico', 'verbose_name_plural': 'Informes Terapéuticos'},
        ),
        migrations.AddField(
            model_name='informesterapeuticos',
            name='Insitucional_a_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Institcuinal', to='usuarios.perfilinstitucional', verbose_name='Responsable institucional'),
        ),
        migrations.AddField(
            model_name='informesterapeuticos',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='informesterapeuticos',
            name='archivo',
            field=models.FileField(upload_to='informes/'),
        ),
        migrations.AlterField(
            model_name='informesterapeuticos',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='informesterapeuticos',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='usuarios.profile'),
        ),
        migrations.AlterField(
            model_name='informesterapeuticos',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
