# Generated by Django 4.2.20 on 2025-07-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_cita_tipo_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='dias_recurrentes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Días de la semana recurrentes'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha en la que dejarán de repetirse las citas', null=True, verbose_name='Fecha fin de terapias'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='tarea_realizada',
            field=models.BooleanField(default=False, verbose_name='¿Paciente Culminó la  Terápia ?'),
        ),
    ]
