# Generated by Django 4.2.20 on 2025-07-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_cita_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={},
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
