# Generated by Django 4.2.20 on 2025-04-15 13:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0007_alter_cita_options_alter_mensaje_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha'], 'verbose_name': 'Administrativos / Cita', 'verbose_name_plural': 'Registros Administrativos / Citas'},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Mensajes MEDDES', 'verbose_name_plural': 'Bandeja de entrada MEDDES'},
        ),
        migrations.AlterModelOptions(
            name='prospecion_administrativa',
            options={'ordering': ['user'], 'verbose_name': 'Administrativo / prospeciónes', 'verbose_name_plural': 'Registros Administrativos / prospeción'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Paciente_nombre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nombre_factura',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='representante_legal_apellido',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='representante_legal_nombre',
        ),
        migrations.AddField(
            model_name='profile',
            name='actividad_economica',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Actividad económica del representante'),
        ),
        migrations.AddField(
            model_name='profile',
            name='apellidos_paciente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='apellidos_representante_legal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='celular',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+593', max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono celular de contacto'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de tratamiento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_terminacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de terminación de tratamiento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nombre_paciente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nombres_representante_legal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='profile',
            name='relacion_del_representante',
            field=models.CharField(blank=True, choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hermano/a', 'Hermano/a'), ('Tío/a', 'Tío/a'), ('Abuelo/a', 'Abuelo/a'), ('Ñeto/a', 'Ñeto/a'), ('Tutor/a', 'Tutor/a'), ('Otro', 'Otro')], max_length=255, null=True, verbose_name='Relación del representante con el paciente'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tipo_servicio',
            field=models.TextField(blank=True, null=True, verbose_name='Servicios Trapeuticos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='valorizacion_terapeutica',
            field=models.TextField(blank=True, null=True, verbose_name='Valoración Terapéutica'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Foto Perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ruc',
            field=models.CharField(blank=True, help_text='R.U.C o C.I del Representante', max_length=13, null=True, verbose_name='RUC / C.I'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+593', max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono convencional de contacto'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unidad_educativa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unidad educativa'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_terapeuta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil_terapeuta', verbose_name='Terapéuta Asignado'),
        ),
        migrations.CreateModel(
            name='tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título de la tarea')),
                ('fecha_envio', models.DateField(blank=True, null=True, verbose_name='Fecha de envio de tarea')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega de tarea')),
                ('material_adjunto', models.FileField(blank=True, upload_to='materiales/%Y/%m/%d/', verbose_name='Material adjunto')),
                ('media_terapia', models.FileField(blank=True, upload_to='Videos/%Y/%m/%d/', verbose_name='Contenido Multimedia de Terapia')),
                ('descripcion_tarea', models.TextField(blank=True, null=True, verbose_name='Descripción de la tarea')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.profile')),
                ('terapeuta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil_terapeuta', verbose_name='Terapéuta Asignado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de Usuario')),
            ],
            options={
                'verbose_name': 'Paciente/ Tareas',
                'verbose_name_plural': 'Registros de Terapéuticos / Tareas',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de cuenta')),
                ('colegio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del colegio')),
                ('plan', models.CharField(blank=True, choices=[('Institucional', 'Institucional'), ('Domicilio Institucional', 'Domicilio Institucional'), ('Domicilio Familiar', 'Domicilio Familiar'), ('Consultorio Institucional', 'Consultorio Institucional'), ('Becas(100%)', 'Becas(100%)'), ('Becas(50%)', 'Becas(50%)'), ('Domicilio', 'Domicilio'), ('Consultorio', 'Consultorio')], max_length=255, null=True, verbose_name='Plan Económico')),
                ('convenio', models.BooleanField(default=False, verbose_name='Convenio')),
                ('sucursal', models.CharField(blank=True, choices=[('Quito - Valles', 'Quito - Valles'), ('Quito - Centro', 'Quito - Centro'), ('Guayaquil', 'Guayaquil')], max_length=255, null=True, verbose_name='Sucursal')),
                ('servicio', models.CharField(blank=True, choices=[('Terapia de Lenguaje - valoración lenguaje', 'Terapia de Lenguaje - valoración lenguaje'), ('Terapia de Lenguaje - Terapia de lenguaje', 'Terapia de Lenguaje - Terapia de lenguaje'), ('Terapia de Lenguaje - paquete mensual(8 sesiones)', 'Terapia de Lenguaje - paquete mensual(8 sesiones)'), ('Terapia de Lenguaje - paquete mensual(24 sesiones)', 'Terapia de Lenguaje - paquete mensual(24 sesiones)'), ('Psicología - valoración Psicologica', 'Psicología - valoración Psicologica'), ('Psicología - valoración Psicopedagogica', 'Psicología - valoración Psicopedagogica'), ('Psicología - Terapia Psicologica', 'Psicología - Terapia Psicologica'), ('Psicología - Terapia Psicologica de pareja', 'Psicología - Terapia Psicologica de pareja'), ('Psicología - Paquete mensual de terapia (4 sesiones)', 'Psicología - Paquete mensual de terapia (4 sesiones)'), ('Psicología - Paquete mensual de terapia (12 sesiones)', 'Psicología - Paquete mensual de terapia (12 sesiones)'), ('Psicología - Paquete mensual de terapia de pareja', 'Psicología - Paquete mensual de terapia de pareja'), ('Psicología - Paquete mensual de terapia de pareja (12 sesiones)', 'Psicología - Paquete mensual de terapia de pareja (12 sesiones)'), ('Estimulación Cognitiva Adulto Mayor - Individual', 'Estimulación Cognitiva Adulto Mayor - Individual'), ('Estimulación Cognitiva Adulto Mayor - grupal (3-5)', 'Estimulación Cognitiva Adulto Mayor - grupal (3-5)'), ('Estimulación Cognitiva Adulto Mayor - Individual (8 sesiones)', 'Estimulación Cognitiva Adulto Mayor - Individual (8 sesiones)'), ('Audiologia Ocupacional', 'Audiologia Ocupacional'), ('Audiologia escolar', 'Audiologia escolar'), ('Audiologia - Limpieza de Oido', 'Audiologia - Limpieza de Oido'), ('Audiologia- lavado de oido', 'Audiologia- lavado de oido')], max_length=255, null=True, verbose_name='Servicio terapéutico')),
                ('fecha_emision_factura', models.DateField(blank=True, null=True, verbose_name='Fecha de emisión de factura')),
                ('pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo a cancelar')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento de pago')),
                ('estado_de_pago', models.CharField(blank=True, choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pendiente'), ('Vencido', 'Vencido')], max_length=255, null=True, verbose_name='Estado de pago')),
                ('comprobante_pago', models.FileField(blank=True, upload_to='comprobantes/%Y/%m/%d/', verbose_name='Comprobante de pago')),
                ('numero_de_comprobante', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de comprobante de pago')),
                ('banco', models.CharField(blank=True, choices=[('Banco Pichincha', 'Banco Pichincha'), ('Banco del Pacífico', 'Banco del Pacífico'), ('Produbanco', 'Produbanco'), ('Banco Internacional', 'Banco Internacional'), ('Banco Bolivariano', 'Banco Bolivariano'), ('Banco de Guayaquil', 'Banco de Guayaquil'), ('Banco del Austro', 'Banco del Austro'), ('Banco Solidario', 'Banco Solidario'), ('Cooperativa JEP', 'Cooperativa JEP'), ('Cooperativa 29 de Octubre', 'Cooperativa 29 de Octubre'), ('Cooperativa Policía Nacional', 'Cooperativa Policía Nacional'), ('Banco Central del Ecuador', 'Banco Central del Ecuador'), ('Banco Amazonas', 'Banco Amazonas'), ('Banco ProCredit', 'Banco ProCredit'), ('Banco Diners Club', 'Banco Diners Club'), ('Banco General Rumiñahui', 'Banco General Rumiñahui'), ('Banco Coopnacional', 'Banco Coopnacional'), ('Otros', 'Otros'), ('No aplica', 'No aplica')], max_length=255, null=True, verbose_name='Institución bancaria de Pago')),
                ('metodo_pago', models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Transferencia Bancaria', 'Transferencia Bancaria'), ('Electónica - PayPhone', 'Electónica - PayPhone'), ('Electónica - DataFast', 'Electónica - DataFast')], max_length=255, null=True, verbose_name='Método de Pago')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de Usuario')),
            ],
            options={
                'verbose_name': 'Administrativo / Pagos servicios ',
                'verbose_name_plural': 'Registros Administrativos / Pagos de servicios',
                'ordering': ['fecha_emision_factura'],
            },
        ),
    ]
