# Generated by Django 4.2.24 on 2025-10-15 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_profile_es_en_convenio_alter_profile_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informesterapeuticos',
            name='terapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primer_terapeuta_informes', to='usuarios.perfil_terapeuta', verbose_name='Terapéuta Responsable'),
        ),
    ]
