# Generated by Django 4.2.23 on 2025-08-27 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0007_alter_informesterapeuticos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracionterapia',
            name='terapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terapeuta_asiganados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='informesterapeuticos',
            name='archivo',
            field=models.FileField(upload_to='informes/', verbose_name='Informe'),
        ),
    ]
