# Generated by Django 4.2.24 on 2025-10-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_informesterapeuticos_terapeuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nombre_institucion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de Institución sin convenio'),
        ),
    ]
