# Generated by Django 4.2.23 on 2025-08-27 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_valoracionterapia_terapeuta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='hora_fin',
        ),
        migrations.AlterField(
            model_name='valoracionterapia',
            name='terapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terapeuta_asiganados', to='usuarios.perfil_terapeuta', verbose_name='Terapeuta que realiza la valoración'),
        ),
    ]
