# Generated by Django 4.2.20 on 2025-04-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_cita_options_alter_mensaje_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nacionalidad_representante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='profile',
            name='provincia',
            field=models.CharField(blank=True, choices=[('Azuay', 'Azuay'), ('Bolívar', 'Bolívar'), ('Cañar', 'Cañar'), ('Carchi', 'Carchi'), ('Chimborazo', 'Chimborazo'), ('Cotopaxi', 'Cotopaxi'), ('El Oro', 'El Oro'), ('Esmeraldas', 'Esmeraldas'), ('Galápagos', 'Galápagos'), ('Guayas', 'Guayas'), ('Imbabura', 'Imbabura'), ('Loja', 'Loja'), ('Los Ríos', 'Los Ríos'), ('Manabí', 'Manabí'), ('Morona Santiago', 'Morona Santiago'), ('Napo', 'Napo'), ('Orellana', 'Orellana'), ('Pastaza', 'Pastaza'), ('Pichincha', 'Pichincha'), ('Santa Elena', 'Santa Elena'), ('Santo Domingo de los Tsáchilas', 'Santo Domingo de los Tsáchilas'), ('Sucumbíos', 'Sucumbíos'), ('Tungurahua', 'Tungurahua'), ('Zamora Chinchipe', 'Zamora Chinchipe')], default='Pichincha', max_length=255, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ruc_representante',
            field=models.CharField(blank=True, help_text='R.U.C o C.I del Representante', max_length=13, null=True, verbose_name='RUC / C.I'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ruc',
            field=models.CharField(blank=True, help_text='Ingrese C.I del Paciente', max_length=13, null=True, verbose_name='C.I Paciente'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('Terapia de Lenguaje - valoración lenguaje', 'Terapia de Lenguaje - valoración lenguaje'), ('Terapia de Lenguaje - Terapia de lenguaje', 'Terapia de Lenguaje - Terapia de lenguaje'), ('Terapia de Lenguaje - paquete mensual(8 sesiones)', 'Terapia de Lenguaje - paquete mensual(8 sesiones)'), ('Terapia de Lenguaje - paquete mensual(24 sesiones)', 'Terapia de Lenguaje - paquete mensual(24 sesiones)'), ('Psicología - valoración Psicologica', 'Psicología - valoración Psicologica'), ('Psicología - valoración Psicopedagogica', 'Psicología - valoración Psicopedagogica'), ('Psicología - Terapia Psicologica', 'Psicología - Terapia Psicologica'), ('Psicología - Terapia Psicologica de pareja', 'Psicología - Terapia Psicologica de pareja'), ('Psicología - Paquete mensual de terapia (4 sesiones)', 'Psicología - Paquete mensual de terapia (4 sesiones)'), ('Psicología - Paquete mensual de terapia (12 sesiones)', 'Psicología - Paquete mensual de terapia (12 sesiones)'), ('Psicología - Paquete mensual de terapia de pareja', 'Psicología - Paquete mensual de terapia de pareja'), ('Psicología - Paquete mensual de terapia de pareja (12 sesiones)', 'Psicología - Paquete mensual de terapia de pareja (12 sesiones)'), ('Estimulación Cognitiva Adulto Mayor - Individual', 'Estimulación Cognitiva Adulto Mayor - Individual'), ('Estimulación Cognitiva Adulto Mayor - grupal (3-5)', 'Estimulación Cognitiva Adulto Mayor - grupal (3-5)'), ('Estimulación Cognitiva Adulto Mayor - Individual (8 sesiones)', 'Estimulación Cognitiva Adulto Mayor - Individual (8 sesiones)'), ('Audiologia Ocupacional', 'Audiologia Ocupacional'), ('Audiologia escolar', 'Audiologia escolar'), ('Audiologia - Limpieza de Oido', 'Audiologia - Limpieza de Oido'), ('Audiologia- lavado de oido', 'Audiologia- lavado de oido')], max_length=255, null=True, verbose_name='Servicio terapéutico'),
        ),
    ]
