# Generated by Django 4.2.20 on 2025-07-30 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_cita_options_cita_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informesterapeuticos',
            name='archivo',
            field=models.FileField(upload_to='documentos/pacientes/', verbose_name='Subir informe Terapéutico'),
        ),
        migrations.AlterField(
            model_name='informesterapeuticos',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='usuarios.profile', verbose_name='Informe Terapéutico'),
        ),
        migrations.AlterField(
            model_name='informesterapeuticos',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Tema terapéutico'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='institucion_a_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_institucional', to='usuarios.perfilinstitucional', verbose_name='Asignar responsable institucional'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='Insitucional_a_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_institucionales', to='usuarios.perfilinstitucional', verbose_name='Responsable institucional'),
        ),
        migrations.AlterField(
            model_name='valoracionterapia',
            name='Insitucional_a_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valoraciones_institucionales', to='usuarios.perfilinstitucional', verbose_name='Responsable institucional'),
        ),
    ]
