# Generated by Django 4.2.20 on 2025-07-23 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0008_alter_cita_dias_recurrentes_alter_cita_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='es_inactivo',
            field=models.BooleanField(default=False, verbose_name='Activo/Inactivo'),
        ),
        migrations.CreateModel(
            name='PerfilInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contacto', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='EC')),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('colegio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.prospeccion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
