# Generated by Django 4.2.20 on 2025-04-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_profile_nacionalidad_representante_profile_provincia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='edad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Edad'),
        ),
    ]
