# Generated by Django 4.2.20 on 2025-07-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_informesterapeuticos_archivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='es_capacitacion',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='es_contactado',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='es_convenio_firmado',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='es_en_cita',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='es_en_terapia',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='es_finalizado',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='es_inactivo',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='es_por_contactar',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='es_rechazado',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='es_valoracion',
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='es_capacitacion',
            field=models.BooleanField(default=False, verbose_name='¿Recibió capacitación?'),
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='es_contactado',
            field=models.BooleanField(default=False, verbose_name='¿Ya fue contactado?'),
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='es_convenio_firmado',
            field=models.BooleanField(default=False, verbose_name='¿Firmó convenio?'),
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='es_en_cita',
            field=models.BooleanField(default=False, verbose_name='¿Ya tuvo cita?'),
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='es_en_terapia',
            field=models.BooleanField(default=False, verbose_name='¿Recibe terapia?'),
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='es_finalizado',
            field=models.BooleanField(default=False, verbose_name='¿Finalizó el proceso?'),
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='es_inactivo',
            field=models.BooleanField(default=False, verbose_name='Activo/Inactivo'),
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='es_por_contactar',
            field=models.BooleanField(default=False, verbose_name='¿Se intentó contactar?'),
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='es_rechazado',
            field=models.BooleanField(default=False, verbose_name='¿Fue rechazado?'),
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='es_valoracion',
            field=models.BooleanField(default=False, verbose_name='¿Tuvo valoración?'),
        ),
    ]
