# Generated by Django 4.2.24 on 2026-01-05 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_profile_nombre_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='informesterapeuticos',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.prospeccion', verbose_name='Institución'),
        ),
    ]
