# Generated by Django 4.2.23 on 2025-08-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_tareas_hora_remove_tareas_hora_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informesterapeuticos',
            name='tipo_de_informe',
            field=models.CharField(blank=True, choices=[('INI', 'Inicial'), ('PRO', 'Progreso'), ('ALT', 'Alta')], max_length=3, verbose_name='Tipo de Informe'),
        ),
    ]
