# Generated by Django 4.2.20 on 2025-07-23 21:58

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_prospecion_administrativa_es_inactivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilinstitucional',
            name='numero_contacto',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+593', max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono convencional de contacto'),
        ),
    ]
