# Generated by Django 4.2.23 on 2025-08-27 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0010_informesterapeuticos_tipo_de_informe'),
    ]

    operations = [
        migrations.AddField(
            model_name='informesterapeuticos',
            name='terapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terapeuta_responsable_informe', to=settings.AUTH_USER_MODEL),
        ),
    ]
