# Generated by Django 4.2.20 on 2025-04-15 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_profile_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.profile'),
        ),
    ]
