# Generated by Django 4.2.20 on 2025-07-23 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_perfilinstitucional_numero_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instirucional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instituciones3', to='usuarios.perfilinstitucional', verbose_name='Responsable Institucional'),
        ),
    ]
