# Generated by Django 4.2.20 on 2025-07-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_prospecion_administrativa_es_capacitacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospeccion',
            name='es_en_terapia',
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='es_capacitacion',
            field=models.BooleanField(default=False, verbose_name='¿Se realizo Capacitación?'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='es_contactado',
            field=models.BooleanField(default=False, verbose_name='¿Se realizo Llamada?'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='es_convenio_firmado',
            field=models.BooleanField(default=False, verbose_name='¿Se firma convenio?'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='es_en_cita',
            field=models.BooleanField(default=False, verbose_name='¿Se tuvo Cita?'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='es_por_contactar',
            field=models.BooleanField(default=False, verbose_name='¿Se envío Mail?'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='es_valoracion',
            field=models.BooleanField(default=False, verbose_name='¿Se realizo valoraciones?'),
        ),
    ]
