# Generated by Django 4.2.20 on 2025-04-15 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_pagos_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.profile'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de Factura'),
        ),
    ]
