# Generated by Django 4.2.20 on 2025-07-30 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_prospeccion_es_en_terapia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospeccion',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_prospecion', to='usuarios.sucursal'),
        ),
    ]
