# Generated by Django 4.2.23 on 2025-08-27 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_informesterapeuticos_terapeuta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='terapeutas_asignados',
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='terapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_perfil_terapeuta1', to='usuarios.perfil_terapeuta', verbose_name='Terapeuta asiganado N.-1'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='terapeuta2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_perfil_terapeuta2', to='usuarios.perfil_terapeuta', verbose_name='Terapeuta asiganado N.-2'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='terapeuta3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_perfil_terapeuta3', to='usuarios.perfil_terapeuta', verbose_name='Terapeuta asiganado N.-3'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='terapeuta4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_perfil_terapeuta4', to='usuarios.perfil_terapeuta', verbose_name='Terapeuta asiganado N.-4'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='terapeuta5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_perfil_terapeuta5', to='usuarios.perfil_terapeuta', verbose_name='Terapeuta asiganado N.-5'),
        ),
    ]
