# Generated by Django 4.2.20 on 2025-07-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_profile_instirucional'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilinstitucional',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del Usuario en la Institución'),
        ),
    ]
