# Generated by Django 4.2.20 on 2025-04-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_cita_profile_pagos_numero_factura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha'], 'verbose_name': 'Administrativos / Ingreso de Cita', 'verbose_name_plural': 'Registros Administrativos / Ingreso de Citas'},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'ordering': ['fecha_emision_factura'], 'verbose_name': 'Administrativo / Pagos servicios ', 'verbose_name_plural': 'Registros Administrativos /Ingreso de Pagos por servicios Terapéuticos'},
        ),
        migrations.AlterModelOptions(
            name='perfil_terapeuta',
            options={'ordering': ['user'], 'verbose_name': 'Registro Administrativo / Ingreso de Terapista', 'verbose_name_plural': 'Registro Administrativo / Ingreso de Terapista'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'Registro Administrativo / Ingreso de Paciente', 'verbose_name_plural': 'Registro Administrativo / Ingreso de Paciente'},
        ),
        migrations.AlterModelOptions(
            name='prospecion_administrativa',
            options={'ordering': ['user'], 'verbose_name': 'Administrativo / prospeciónes', 'verbose_name_plural': 'Registros Administrativos / Ingreso de Prospecto de Paciente'},
        ),
        migrations.AlterModelOptions(
            name='tareas',
            options={'ordering': ['user'], 'verbose_name': 'Paciente/ Tareas', 'verbose_name_plural': 'Registros de Terapéuticos / Ingreso de Tareas Terapéuticas'},
        ),
    ]
