# Generated by Django 4.2.20 on 2025-07-30 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_prospeccion_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospeccion',
            name='cargo_ejecutivo_meddes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='ejecutivo_meddes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.administrativeprofile', verbose_name='Ejecutivo Meddes'),
        ),
    ]
