# Generated by Django 4.2.20 on 2025-07-23 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_perfilinstitucional_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='cargo_responsable_1',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='cargo_responsable_2',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='mail_responsable_1',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='mail_responsable_2',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='telefono_responsable_1',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='telefono_responsable_2',
        ),
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='responsable_institucional_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instituciones_asignadas', to='usuarios.perfilinstitucional', verbose_name='Responsable Institucional 1'),
        ),
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='responsable_institucional_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instituciones_asignadas2', to='usuarios.perfilinstitucional', verbose_name='Responsable Institucional 2'),
        ),
    ]
