# Generated by Django 4.2.23 on 2025-09-01 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_remove_prospecion_administrativa_terapeutas_asignados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='actividad_realizada',
            field=models.BooleanField(default=False, verbose_name='¿Realizó la tarea?'),
        ),
        migrations.AlterField(
            model_name='valoracionterapia',
            name='perfil_terapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_terapeuta_asignado', to='usuarios.perfil_terapeuta', verbose_name='Terapeuta Responsable'),
        ),
        migrations.AlterField(
            model_name='valoracionterapia',
            name='terapeuta',
            field=models.ForeignKey(blank=True, help_text='Campo llenado por personal administrativo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terapeuta_asiganados', to='usuarios.perfil_terapeuta', verbose_name='Responsable Terapeutico'),
        ),
    ]
