# Generated by Django 4.2.20 on 2025-07-23 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_remove_prospecion_administrativa_cargo_responsable_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracionterapia',
            name='Insitucional_a_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valoraciones_institucionales', to='usuarios.perfilinstitucional', verbose_name='Institución a cargo'),
        ),
    ]
