# Generated by Django 4.2.20 on 2025-07-30 17:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_prospeccion_cargo_ejecutivo_meddes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospeccion',
            options={'ordering': ['-fecha_contacto'], 'verbose_name': 'Administrativo / Prospecciones', 'verbose_name_plural': 'Registros Administrativos / Prospección'},
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email de Contacto'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='es_capacitacion',
            field=models.BooleanField(default=False, verbose_name='¿Se realizó Capacitación?'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='es_contactado',
            field=models.BooleanField(default=False, verbose_name='¿Se realizó Llamada?'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='es_valoracion',
            field=models.BooleanField(default=False, verbose_name='¿Se realizaron valoraciones?'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='fecha_contacto',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Contacto'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='fecha_proximo_contacto',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Próximo Contacto'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='observaciones',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='provincia',
            field=models.CharField(choices=[('Azuay', 'Azuay'), ('Bolívar', 'Bolívar'), ('Cañar', 'Cañar'), ('Carchi', 'Carchi'), ('Chimborazo', 'Chimborazo'), ('Cotopaxi', 'Cotopaxi'), ('El Oro', 'El Oro'), ('Esmeraldas', 'Esmeraldas'), ('Galápagos', 'Galápagos'), ('Guayas', 'Guayas'), ('Imbabura', 'Imbabura'), ('Loja', 'Loja'), ('Los Ríos', 'Los Ríos'), ('Manabí', 'Manabí'), ('Morona Santiago', 'Morona Santiago'), ('Napo', 'Napo'), ('Orellana', 'Orellana'), ('Pastaza', 'Pastaza'), ('Pichincha', 'Pichincha'), ('Santa Elena', 'Santa Elena'), ('Santo Domingo de los Tsáchilas', 'Santo Domingo de los Tsáchilas'), ('Sucumbíos', 'Sucumbíos'), ('Tungurahua', 'Tungurahua'), ('Zamora Chinchipe', 'Zamora Chinchipe')], max_length=100, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='EC', verbose_name='Teléfono'),
        ),
    ]
