# Generated by Django 4.2.20 on 2025-04-15 22:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_cita_options_alter_pagos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
