# Generated by Django 4.2.20 on 2025-07-23 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_valoracionterapia_insitucional_a_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='Insitucional_a_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_institucionales', to='usuarios.perfilinstitucional', verbose_name='Institución a cargo'),
        ),
    ]
