# Generated by Django 4.2.20 on 2025-04-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_mensaje_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='task_id',
            field=models.CharField(blank=True, help_text='ID de la tarea de Celery asociada', max_length=255, null=True),
        ),
    ]
