# Generated by Django 4.2.20 on 2025-07-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_prospeccion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospeccion',
            name='estado',
        ),
    ]
