# Generated by Django 4.2.20 on 2025-04-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_mensaje_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='task_status',
            field=models.CharField(blank=True, help_text='Estado de la tarea de Celery asociada', max_length=50, null=True),
        ),
    ]
