# Generated by Django 4.2.20 on 2025-07-30 17:40

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_remove_prospeccion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospeccion',
            name='proceso_realizado',
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='responsable',
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+593', max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono de la Institución'),
        ),
    ]
