# Generated by Django 4.2.20 on 2025-07-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_perfil_terapeuta_pago_por_hora_consulta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_terapeuta',
            name='servicio_consulta',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
