# Generated by Django 4.2.20 on 2025-07-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_remove_prospeccion_proceso_realizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='asunto_2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Escriba el Asunto del mensaje'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(choices=[('Consulta', 'Consulta'), ('Sugerencia', 'Sugerencia'), ('Informativo', 'Informativo'), ('Terapéutico', 'Terapéutico'), ('Solicitud de pago vencido', 'Solicitud de pago vencido'), ('Solicitud de Certificado Médico', 'Solicitud de Certificado Médico'), ('Reclamo del servicio Médico', 'Reclamo del servicio Médico'), ('Cancelación del servicio Médico', 'Cancelación del servicio Médico')], default='Consulta', max_length=50, verbose_name='Elija el tipo de Notificación'),
        ),
    ]
