# Generated by Django 4.2.20 on 2025-07-24 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alter_perfil_terapeuta_servicio_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformesTerapeuticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del archivo')),
                ('archivo', models.FileField(upload_to='documentos/pacientes/', verbose_name='Archivo')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='usuarios.profile')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
            },
        ),
    ]
