# Generated by Django 4.2.20 on 2025-04-23 16:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0017_pagos_pago_currency_alter_mensaje_asunto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospecion_administrativa',
            options={'ordering': ['nombre'], 'verbose_name': 'Administrativo / prospeciónes', 'verbose_name_plural': 'Registros Administrativos / Ingreso de Prospecto de Paciente'},
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='user',
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='convenio_pdf',
            field=models.FileField(blank=True, help_text='Cargar archivo en PDF', null=True, upload_to='convenios/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='correo_persona_cargo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='ejecutivo_encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colegios_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='estado',
            field=models.CharField(blank=True, choices=[('por_contactar', 'Por Contactar'), ('contactado', 'Contactado'), ('en_cita', 'En Cita'), ('convenio_firmado', 'Convenio Firmado'), ('capacitacion', 'Capacitación'), ('valoracion', 'Valoración'), ('en_terapia', 'En Terapia'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado'), ('inactivo', 'Inactivo')], default='por_contactar', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='fecha_estado_actualizado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='mails_colegio',
            field=models.TextField(blank=True, help_text='Separar múltiples correos por comas', null=True),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Colegio'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='nombre_persona_cargo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='regional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='telefono_persona_cargo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='telefonos_colegio',
            field=models.TextField(blank=True, help_text='Separar múltiples teléfonos por comas', null=True),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='terapeutas_asignados',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Terapeutas'}, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
