# Generated by Django 4.2.20 on 2025-04-23 16:35

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_alter_prospecion_administrativa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='correo_persona_cargo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico Persona a cargo'),
        ),
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='telefonos_colegio',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+593', max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono de persona a cargo'),
        ),
    ]
