# Generated by Django 4.2.20 on 2025-07-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_informesterapeuticos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informesterapeuticos',
            options={'verbose_name': 'Informe Terapéutico', 'verbose_name_plural': 'Informes Terapéuticos'},
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de finalización la cita'),
        ),
    ]
