# Generated by Django 4.2.20 on 2025-07-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_alter_informesterapeuticos_options_cita_hora_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Tiempo inicial'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Tiempo Final'),
        ),
    ]
