# Generated by Django 4.2.20 on 2025-04-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_alter_prospecion_administrativa_correo_persona_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='antecedentes_penales',
            field=models.FileField(blank=True, null=True, upload_to='documentos/terapeutas/antecedentes/'),
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='certificados',
            field=models.FileField(blank=True, null=True, upload_to='documentos/terapeutas/certificados/'),
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='datos_bancarios',
            field=models.TextField(blank=True, help_text='Ej: Banco, número de cuenta, tipo', null=True),
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='nombres_completos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='pago_por_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='servicio_domicilio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='servicio_institucion',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='tipo_servicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='titulo_universitario',
            field=models.FileField(blank=True, null=True, upload_to='documentos/terapeutas/titulo/'),
        ),
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='mails_colegio',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico de Colegio'),
        ),
    ]
