# Generated by Django 4.2.20 on 2025-07-31 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_alter_profile_user_terapeutas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='comercial_meddes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil_comercial', verbose_name='Comercial Meddes a Cargo'),
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='comercial_meddes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil_comercial', verbose_name='Comercial Meddes a Cargo'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='comercial_meddes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil_comercial', verbose_name='Comercial Meddes'),
        ),
    ]
