# Generated by Django 4.2.20 on 2025-07-31 02:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0020_cita_comercial_meddes_prospeccion_comercial_meddes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil_comercial',
            options={'verbose_name': 'Perfil comercial', 'verbose_name_plural': 'Perfiles comerciales'},
        ),
        migrations.RenameField(
            model_name='perfil_comercial',
            old_name='pago_por_hora_consulta_currency',
            new_name='salary_currency',
        ),
        migrations.RenameField(
            model_name='perfil_comercial',
            old_name='pago_por_hora_currency',
            new_name='valor_por_paciente_currency',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='antecedentes_penales',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='certificados',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='institucional_a_domicilio',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='nombres_completos',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='numero_cuenta',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='pago_por_hora',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='pago_por_hora_consulta',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='pago_por_hora_institucion',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='pago_por_hora_institucion_currency',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='pago_por_hora_institucional_a_domicilio',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='pago_por_hora_institucional_a_domicilio_currency',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='servicio_consulta',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='servicio_domicilio',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='servicio_institucion',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='tipo_cuenta',
        ),
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='titulo_universitario',
        ),
        migrations.AddField(
            model_name='perfil_comercial',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección de Domicilio'),
        ),
        migrations.AddField(
            model_name='perfil_comercial',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('FT', 'Tiempo completo'), ('PT', 'Medio tiempo'), ('CT', 'Contrato temporal')], max_length=2, null=True, verbose_name='Tipo de contrato'),
        ),
        migrations.AddField(
            model_name='perfil_comercial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil_comercial',
            name='date_joined',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='perfil_comercial',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='perfil_comercial',
            name='department',
            field=models.CharField(blank=True, choices=[('gerencia', 'Gerencia'), ('administracion', 'Administración'), ('financiero', 'Financiero'), ('operativo', 'Operativo')], max_length=30, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='perfil_comercial',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='perfil_comercial',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='perfil_comercial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='perfil_comercial',
            name='job_title',
            field=models.CharField(blank=True, choices=[('gerente_general', 'Gerente General'), ('gerente_comercial', 'Ejecutivo Comercial'), ('tecnico_administrativo', 'Técnico Administrativo'), ('asistente_administrativo', 'Asistente Administrativo'), ('terapeuta', 'Terapéuta'), ('contador', 'Contador'), ('analista_financiero', 'Analista Financiero'), ('jefe_finanzas', 'Jefe de Finanzas')], max_length=50, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='perfil_comercial',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula de identidad'),
        ),
        migrations.AddField(
            model_name='perfil_comercial',
            name='num_pacientes_captados',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Número de pacientes adquiridos por este comercial', null=True, verbose_name='Pacientes captados'),
        ),
        migrations.AddField(
            model_name='perfil_comercial',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Hoja de vida'),
        ),
        migrations.AddField(
            model_name='perfil_comercial',
            name='salary',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=10, null=True, verbose_name='Valor base'),
        ),
        migrations.AddField(
            model_name='perfil_comercial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil_comercial',
            name='valor_por_paciente',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', help_text='Valor por paciente / Comisión', max_digits=10, null=True, verbose_name='Valor por paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo_cita',
            field=models.CharField(blank=True, choices=[('administrativa', 'Administrativa'), ('terapeutica', 'Terapéutica'), ('particular', 'Particular'), ('comercial', 'Comercial')], default='terapeutica', max_length=20, null=True, verbose_name='Categoría de Cita'),
        ),
        migrations.AlterField(
            model_name='perfil_comercial',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+593', max_length=128, null=True, region=None, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='perfil_comercial',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_comercial', to=settings.AUTH_USER_MODEL),
        ),
    ]
