# Generated by Django 4.2.20 on 2025-07-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_alter_cita_hora_alter_cita_hora_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='hora de inicio'),
        ),
        migrations.AddField(
            model_name='tareas',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de finalización'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='cita_terapeutica_asignada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Sesion de Terapia'),
        ),
    ]
