# Generated by Django 4.2.20 on 2025-07-31 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_alter_perfil_comercial_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_comercial',
            name='date_of_birth',
        ),
    ]
