# Generated by Django 4.2.20 on 2025-07-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_tareas_hora_tareas_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareacomentario',
            options={'ordering': ['fecha'], 'verbose_name': 'Revisar Tarea Terapeutica', 'verbose_name_plural': 'Revisar Tareas'},
        ),
        migrations.AddField(
            model_name='tareas',
            name='envio_tarea',
            field=models.BooleanField(default=False, verbose_name='¿Se envía tarea? No/Si'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='asistire',
            field=models.BooleanField(default=False, verbose_name='¿Asistió? No/Si'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='tarea_realizada',
            field=models.BooleanField(default=False, verbose_name='¿Tiene Alta Terapéutica? No/Si'),
        ),
    ]
