# Generated by Django 4.2.20 on 2025-04-23 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_asistenciaterapeuta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistenciaterapeuta',
            name='cita_relacionada',
        ),
    ]
