# Generated by Django 4.2.20 on 2025-04-23 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('usuarios', '0022_remove_asistenciaterapeuta_cita_relacionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaterapeuta',
            name='evento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.event'),
        ),
    ]
