# Generated by Django 4.2.20 on 2025-07-24 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_alter_tareacomentario_options_tareas_envio_tarea_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Notificaciones de MEDDES®', 'verbose_name_plural': 'Bandeja de entrada MEDDES®'},
        ),
        migrations.AddField(
            model_name='mensaje',
            name='institucion_a_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_institucional', to='usuarios.perfilinstitucional', verbose_name='Asignar institución a cargo'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='perfil_administrativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_administrativo', to='usuarios.administrativeprofile', verbose_name='Asignar administrativo'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='perfil_paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_perfil_paciente', to='usuarios.profile', verbose_name='Asignar a perfil de paciente'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='perfil_terapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_perfil_terapeuta', to='usuarios.perfil_terapeuta', verbose_name='Asignar terapeuta'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(choices=[('Consulta', 'Consulta'), ('Sugerencia', 'Sugerencia'), ('Informativo', 'Informativo'), ('Terapéutico', 'Terapéutico'), ('Solicitud de pago vencido', 'Solicitud de pago vencido'), ('Solicitud de Certificado Médico', 'Solicitud de Certificado Médico'), ('Reclamo del servicio Médico', 'Reclamo del servicio Médico'), ('Cancelación del servicio Médico', 'Cancelación del servicio Médico')], default='Consulta', max_length=50),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Asignar_perfil_de_paciente2', to='usuarios.profile', verbose_name='Paciente Asignado'),
        ),
    ]
