# Generated by Django 4.2.20 on 2025-07-24 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_alter_mensaje_options_mensaje_institucion_a_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='perfil_paciente',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='usuarios.administrativeprofile', verbose_name='Administrador emisor'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_perfil_paciente', to='usuarios.profile', verbose_name='Asignar a perfil de paciente'),
        ),
    ]
