# Generated by Django 4.2.20 on 2025-04-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_asistenciaterapeuta_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
