# Generated by Django 4.2.20 on 2025-04-24 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0024_cita_fecha_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraDesarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_cambio', models.CharField(choices=[('Registro administrativo/Perfil de Paciente', 'RAPP'), ('Registro administrativo/Perfil de Terapistas', 'RAPT'), ('Registro administrativo/Agenda de Citas Regulares', 'RAACC'), ('Registro administrativo/Prospeción Administrativa', 'RAPA'), ('Registro administrativo/Pago de Servicios', 'RAPS'), ('Registro Terapeutico/Tareas & Actividades', 'RTTA'), ('Registro Terapeutico/Asistencias', 'RTAA'), ('Bandeja de Notificaciones', 'SBN'), ('Visualización de ERP', 'SERP')], max_length=200)),
                ('version_relacionada', models.CharField(blank=True, choices=[('QND-0.3.0.1', 'QND0301'), ('QND-0.3.0.2', 'QND0302'), ('QND-0.3.0.3', 'QND0303'), ('QND-0.3.0.4', 'QND0304')], max_length=200, null=True)),
                ('tipo_tecnologia', models.CharField(choices=[('Experiencia de Usuario', 'UX'), ('Interfase', 'UI'), ('Implementación', 'I+D'), ('Automatización', 'A')], max_length=200)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Bitácora',
                'verbose_name_plural': 'Bitácora de Desarrollo QND.0.3.0.1',
                'ordering': ['-fecha'],
            },
        ),
    ]
