# Generated by Django 4.2.20 on 2025-07-25 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_remove_mensaje_perfil_paciente_alter_mensaje_emisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='emisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_enviados', to='usuarios.administrativeprofile', verbose_name='Administrador emisor'),
        ),
    ]
