# Generated by Django 4.2.20 on 2025-07-25 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_alter_mensaje_emisor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'Registro Administrativo / Historial de Paciente', 'verbose_name_plural': 'Registro Administrativo / Historiales de Pacientes'},
        ),
    ]
