# Generated by Django 4.2.20 on 2025-04-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_bitacoradesarrollo_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoradesarrollo',
            name='sqcrew',
            field=models.CharField(blank=True, choices=[('DeV', 'Desarollo - backend'), ('DeV', 'Desarollo - frontend'), ('DeV', 'Desarollo - fullstack'), ('DeV', 'Desarollo - QA'), ('DeV', 'Desarollo - UI/UX'), ('DeV', 'Desarollo - I+D'), ('ProD', 'Producción -backend'), ('ProD', 'Producción - frontend'), ('ProD', 'Producción - fullstack'), ('ProD', 'Producción - QA'), ('ProD', 'Producción - UI/UX'), ('ProD', 'Producción - I+D'), ('StG', 'Soporte - backend'), ('StG', 'Soporte - frontend'), ('StG', 'Soporte - fullstack'), ('StG', 'Soporte - QA'), ('StG', 'Soporte - UI/UX'), ('StG', 'Soporte - I+D'), ('StG', 'Soporte - Producción'), ('DA', 'Data Analytics')], max_length=200, null=True),
        ),
    ]
