# Generated by Django 4.2.20 on 2025-07-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='mensajes_adjuntos/', verbose_name='Archivo adjunto'),
        ),
    ]
