# Generated by Django 4.2.20 on 2025-04-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_bitacoradesarrollo_sqcrew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacoradesarrollo',
            old_name='sqcrew',
            new_name='smart_quail_crew',
        ),
    ]
