# Generated by Django 4.2.20 on 2025-07-25 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_mensaje_adjunto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrativeprofile',
            old_name='phone_number',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='perfil_terapeuta',
            old_name='telefonos_contacto',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='perfilinstitucional',
            old_name='numero_contacto',
            new_name='telefono',
        ),
    ]
