# Generated by Django 4.2.20 on 2025-04-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_rename_sqcrew_bitacoradesarrollo_smart_quail_crew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bitacoradesarrollo',
            old_name='smart_quail_crew',
            new_name='SmartQuail_crew',
        ),
    ]
