# Generated by Django 4.2.20 on 2025-04-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0030_rename_smartquail_crew_bitacoradesarrollo_smartquail_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoradesarrollo',
            name='progreso',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bitacoradesarrollo',
            name='version_relacionada',
            field=models.CharField(blank=True, choices=[('QND0301', 'QND-0.3.0.1'), ('QND0302', 'QND-0.3.0.2'), ('QND0303', 'QND-0.3.0.3'), ('QND0304', 'QND-0.3.0.4')], max_length=200, null=True, verbose_name='Versión'),
        ),
    ]
