# Generated by Django 4.2.20 on 2025-04-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_bitacoradesarrollo_progreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoradesarrollo',
            name='estado',
            field=models.CharField(blank=True, choices=[('Desarollo', 'Desarollo'), ('Pruebas', 'Pruebas'), ('Producción', 'Producción'), ('Aprobado', 'Aprobado')], max_length=200, null=True, verbose_name='ESTADO'),
        ),
        migrations.AlterField(
            model_name='bitacoradesarrollo',
            name='version_relacionada',
            field=models.CharField(blank=True, choices=[('QND0301', 'QND-0.3.0.1'), ('QND0302', 'QND-0.3.0.2'), ('QND0303', 'QND-0.3.0.3'), ('QND0304', 'QND-0.3.0.4')], default='QND-0.3.0.1', max_length=200, null=True, verbose_name='Versión'),
        ),
    ]
