# Generated by Django 4.2.20 on 2025-04-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0032_bitacoradesarrollo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoradesarrollo',
            name='estado',
            field=models.CharField(blank=True, choices=[('Revisión', 'Revisión'), ('Desarollo', 'Desarollo'), ('Pruebas', 'Pruebas'), ('Producción', 'Producción'), ('Aprobado', 'Aprobado')], default='Revisión', max_length=200, null=True, verbose_name='ESTADO'),
        ),
    ]
