# Generated by Django 4.2.20 on 2025-04-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0033_alter_bitacoradesarrollo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
