# Generated by Django 4.2.20 on 2025-05-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0036_alter_pagos_pago_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospecion_administrativa',
            options={'ordering': ['nombre'], 'verbose_name': 'Administrativo / prospeciónes', 'verbose_name_plural': 'Registros Administrativos / Ingreso perfil de colegio'},
        ),
        migrations.AddField(
            model_name='asistenciaterapeuta',
            name='sucursal',
            field=models.CharField(blank=True, choices=[('Quito - Valles', 'Quito - Valles'), ('Quito - Centro', 'Quito - Centro'), ('Guayaquil', 'Guayaquil'), ('Manta', 'Manta')], max_length=255, null=True, verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='cita',
            name='sucursal',
            field=models.CharField(blank=True, choices=[('Quito - Valles', 'Quito - Valles'), ('Quito - Centro', 'Quito - Centro'), ('Guayaquil', 'Guayaquil'), ('Manta', 'Manta')], max_length=255, null=True, verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='sucursal',
            field=models.CharField(blank=True, choices=[('Quito - Valles', 'Quito - Valles'), ('Quito - Centro', 'Quito - Centro'), ('Guayaquil', 'Guayaquil'), ('Manta', 'Manta')], max_length=255, null=True, verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='sucursal',
            field=models.CharField(blank=True, choices=[('Quito - Valles', 'Quito - Valles'), ('Quito - Centro', 'Quito - Centro'), ('Guayaquil', 'Guayaquil'), ('Manta', 'Manta')], max_length=255, null=True, verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sucursal',
            field=models.CharField(blank=True, choices=[('Quito - Valles', 'Quito - Valles'), ('Quito - Centro', 'Quito - Centro'), ('Guayaquil', 'Guayaquil'), ('Manta', 'Manta')], max_length=255, null=True, verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='sucursal',
            field=models.CharField(blank=True, choices=[('Quito - Valles', 'Quito - Valles'), ('Quito - Centro', 'Quito - Centro'), ('Guayaquil', 'Guayaquil'), ('Manta', 'Manta')], max_length=255, null=True, verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='tareas',
            name='sucursal',
            field=models.CharField(blank=True, choices=[('Quito - Valles', 'Quito - Valles'), ('Quito - Centro', 'Quito - Centro'), ('Guayaquil', 'Guayaquil'), ('Manta', 'Manta')], max_length=255, null=True, verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='sucursal',
            field=models.CharField(blank=True, choices=[('Quito - Valles', 'Quito - Valles'), ('Quito - Centro', 'Quito - Centro'), ('Guayaquil', 'Guayaquil'), ('Manta', 'Manta')], max_length=255, null=True, verbose_name='Sucursal'),
        ),
    ]
