# Generated by Django 4.2.20 on 2025-05-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0037_alter_prospecion_administrativa_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(max_length=100, verbose_name='DISTRITO')),
                ('provincia', models.CharField(max_length=100, verbose_name='PROVINCIA')),
                ('zona', models.CharField(max_length=100, verbose_name='ZONA')),
                ('nombre_institucion', models.CharField(max_length=200, verbose_name='NOMBRE DE LA INSTITUCIÓN')),
                ('sostenimiento', models.CharField(max_length=100, verbose_name='SOSTENIMIENTO')),
                ('estado', models.CharField(max_length=100, verbose_name='ESTADO')),
                ('telefono', models.CharField(max_length=20, verbose_name='TELEFONO')),
                ('sector', models.CharField(max_length=100, verbose_name='SECTOR')),
                ('direccion', models.CharField(max_length=250, verbose_name='DIRECCION')),
                ('tl_nombre_contacto', models.CharField(max_length=200, verbose_name='TERAPIA DE LENGUAJE \nNOMBRE DE CONTACTO')),
                ('tl_cargo_contacto', models.CharField(max_length=200, verbose_name='TERAPIA DE LENGUAJE \nCARGO CONTACTO')),
                ('tl_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='TERAPIA DE LENGUAJE \nEMAIL')),
                ('tl_proceso_realizado', models.TextField(blank=True, verbose_name='TERAPIA DE LENGUAJE\nPROCESO REALIZADO')),
                ('tl_responsable', models.CharField(blank=True, max_length=200, verbose_name='TERAPIA DE LENGUAJE\nRESPONSABLE')),
                ('tl_fecha_contacto', models.DateField(blank=True, null=True, verbose_name='TERAPIA DE LENGUAJE\nFECHA DE CONTACTO')),
                ('tl_observaciones', models.TextField(blank=True, verbose_name='TL\nGENERAL OBSERVACIONES')),
                ('tl_fecha_proximo_contacto', models.DateField(blank=True, null=True, verbose_name='TL\nFECHA PROXIMO CONTACTO')),
                ('psicologia_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='PSICOLOGIA\nEMAIL')),
                ('psicologia_observaciones', models.TextField(blank=True, verbose_name='P\nGENERAL OBSERVACIONES')),
                ('psicologia_fecha_proximo_contacto', models.DateField(blank=True, null=True, verbose_name='P\nFECHA PROXIMO CONTACTO')),
                ('vya_observacion', models.TextField(blank=True, verbose_name='VYA\nOBSERVACIÓN')),
                ('vya_observaciones', models.TextField(blank=True, verbose_name='VYA\nGENERAL OBSERVACIONES')),
                ('vya_fecha_proximo_contacto', models.DateField(blank=True, null=True, verbose_name='VYA\nFECHA PROXIMO\n CONTACTO')),
            ],
        ),
    ]
