# Generated by Django 4.2.20 on 2025-05-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0038_prospeccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospeccion',
            name='telefono',
            field=models.CharField(max_length=100, verbose_name='TELEFONO'),
        ),
    ]
