# Generated by Django 4.2.20 on 2025-05-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0039_alter_prospeccion_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospeccion',
            options={'ordering': ['tl_fecha_contacto'], 'verbose_name': 'Administrativo / Prospecciones', 'verbose_name_plural': 'Registros Administrativos / Prospección '},
        ),
        migrations.AlterModelOptions(
            name='prospecion_administrativa',
            options={'ordering': ['nombre'], 'verbose_name': 'Administrativo / Colegios', 'verbose_name_plural': 'Registros Administrativos / Ingreso perfil de colegio'},
        ),
    ]
