# Generated by Django 4.2.20 on 2025-05-12 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0040_alter_prospeccion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='estado_de_pago',
            field=models.CharField(blank=True, choices=[('Al día', 'Al día'), ('Pendiente', 'Pendiente'), ('Vencido', 'Vencido')], max_length=255, null=True, verbose_name='Estado de pago'),
        ),
    ]
