# Generated by Django 4.2.20 on 2025-05-13 13:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0041_mensaje_creado_alter_pagos_estado_de_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_terapeuta',
            name='datos_bancarios',
            field=models.TextField(blank=True, help_text='Ej: Banco, número de cuenta,cedula, tipo', null=True),
        ),
        migrations.AlterField(
            model_name='perfil_terapeuta',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='EC'),
        ),
    ]
