# Generated by Django 4.2.20 on 2025-05-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0043_remove_perfil_terapeuta_telefono_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareas',
            options={'ordering': ['paciente'], 'verbose_name': 'Paciente/ Tareas', 'verbose_name_plural': 'Registros de Terapéuticos / Ingreso de Tareas Terapéuticas'},
        ),
        migrations.RenameField(
            model_name='tareas',
            old_name='user',
            new_name='paciente',
        ),
        migrations.AddField(
            model_name='tareas',
            name='realizada',
            field=models.BooleanField(default=False, verbose_name='Paciente realizó la tarea asiganda?'),
        ),
    ]
