# Generated by Django 4.2.20 on 2025-05-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0044_alter_tareas_options_rename_user_tareas_paciente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagos',
            old_name='user',
            new_name='cliente',
        ),
    ]
