# Generated by Django 4.2.20 on 2025-05-20 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0045_rename_user_pagos_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Comentario o actividad')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='tareas_respuestas/%Y/%m/%d/', verbose_name='Archivo adjunto')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='usuarios.tareas')),
            ],
            options={
                'verbose_name': 'Comentario de tarea',
                'verbose_name_plural': 'Comentarios de tareas',
                'ordering': ['fecha'],
            },
        ),
    ]
