# Generated by Django 4.2.20 on 2025-05-21 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0046_tareacomentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='usuarios.cita')),
            ],
        ),
    ]
