# Generated by Django 4.2.20 on 2025-05-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0047_comentariocita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Sucursal')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefonos', models.CharField(help_text='Separar múltiples teléfonos con comas.', max_length=100, verbose_name='Teléfonos de Contacto')),
                ('persona_encargada', models.CharField(max_length=100, verbose_name='Persona Encargada')),
                ('correo', models.EmailField(max_length=254, verbose_name='Mail de la Sucursal')),
            ],
        ),
    ]
