# Generated by Django 4.2.20 on 2025-05-21 14:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0048_sucursal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospecion_administrativa',
            options={'ordering': ['nombre'], 'verbose_name': 'Administrativo / Institución', 'verbose_name_plural': 'Registros Administrativos / Ingreso perfil de institución'},
        ),
        migrations.RenameField(
            model_name='prospecion_administrativa',
            old_name='nombre_persona_cargo',
            new_name='cargo_ejecutivo_meddes',
        ),
        migrations.RenameField(
            model_name='prospecion_administrativa',
            old_name='telefono_persona_cargo',
            new_name='telefono_ejecutivo_meddes',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='correo_persona_cargo',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='ejecutivo_encargado',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='mails_colegio',
        ),
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='regional',
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='cargo_responsable_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='cargo_responsable_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='ejecutivo_meddes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instituciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutivo Meddes'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='mail_ejecutivo_meddes',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='mail_institucion_general',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Mail General de la Institución'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='mail_responsable_1',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='mail_responsable_2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='responsable_institucional_1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Responsable Institucional 1'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='responsable_institucional_2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Responsable Institucional 2'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='telefono_responsable_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='telefono_responsable_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la Institución'),
        ),
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='telefonos_colegio',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+593', max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono de la Institución'),
        ),
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='terapeutas_asignados',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'Terapeutas'}, to=settings.AUTH_USER_MODEL, verbose_name='Profesionales asignados'),
        ),
        migrations.CreateModel(
            name='DocenteCapacitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_capacitacion', models.DateField()),
                ('area_capacitacion', models.CharField(choices=[('lenguaje', 'Lenguaje'), ('psicologia', 'Psicología')], max_length=50)),
                ('tema', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('cedula', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes_capacitados', to='usuarios.prospecion_administrativa')),
            ],
            options={
                'verbose_name': 'Docente Capacitado',
                'verbose_name_plural': 'Docentes Capacitados',
            },
        ),
    ]
