# Generated by Django 4.2.20 on 2025-05-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0049_alter_prospecion_administrativa_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoracionTerapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_valoracion', models.CharField(choices=[('particular', 'Particular'), ('convenio', 'En Convenio')], max_length=20, verbose_name='Tipo de Valoración')),
                ('fecha_valoracion', models.DateField(verbose_name='Fecha de Valoración')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('grado', models.CharField(blank=True, max_length=100, null=True)),
                ('servicio', models.CharField(max_length=100, verbose_name='Servicio')),
                ('sucursal', models.CharField(blank=True, choices=[('Quito - Valles', 'Quito - Valles'), ('Quito - Centro', 'Quito - Centro'), ('Guayaquil', 'Guayaquil'), ('Manta', 'Manta')], max_length=255, null=True)),
                ('proceso_terapia', models.BooleanField(default=False, verbose_name='Proceso de Terapia')),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('fecha_asesoria', models.DateField(blank=True, null=True)),
                ('recibe_asesoria', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='valoraciones/adjuntos/')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.prospecion_administrativa', verbose_name='Institución')),
                ('perfil_terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='usuarios.perfil_terapeuta', verbose_name='Terapeuta Asignado')),
            ],
            options={
                'verbose_name': 'Valoración Terapéutica',
                'verbose_name_plural': 'Valoraciones Terapéuticas',
                'ordering': ['-fecha_valoracion'],
            },
        ),
    ]
