# Generated by Django 4.2.20 on 2025-05-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0050_valoracionterapia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioTerapeutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('Terapia de Lenguaje - valoración lenguaje', 'Terapia de Lenguaje - valoración lenguaje'), ('Terapia de Lenguaje - Terapia de lenguaje', 'Terapia de Lenguaje - Terapia de lenguaje'), ('Terapia de Lenguaje - paquete mensual(8 sesiones)', 'Terapia de Lenguaje - paquete mensual(8 sesiones)'), ('Terapia de Lenguaje - paquete mensual(24 sesiones)', 'Terapia de Lenguaje - paquete mensual(24 sesiones)'), ('Psicología - valoración Psicologica', 'Psicología - valoración Psicologica'), ('Psicología - valoración Psicopedagogica', 'Psicología - valoración Psicopedagogica'), ('Psicología - Terapia Psicologica', 'Psicología - Terapia Psicologica'), ('Psicología - Terapia Psicologica de pareja', 'Psicología - Terapia Psicologica de pareja'), ('Psicología - Paquete mensual de terapia (4 sesiones)', 'Psicología - Paquete mensual de terapia (4 sesiones)'), ('Psicología - Paquete mensual de terapia (12 sesiones)', 'Psicología - Paquete mensual de terapia (12 sesiones)'), ('Psicología - Paquete mensual de terapia de pareja', 'Psicología - Paquete mensual de terapia de pareja'), ('Psicología - Paquete mensual de terapia de pareja (12 sesiones)', 'Psicología - Paquete mensual de terapia de pareja (12 sesiones)'), ('Estimulación Cognitiva Adulto Mayor - Individual', 'Estimulación Cognitiva Adulto Mayor - Individual'), ('Estimulación Cognitiva Adulto Mayor - grupal (3-5)', 'Estimulación Cognitiva Adulto Mayor - grupal (3-5)'), ('Estimulación Cognitiva Adulto Mayor - Individual (8 sesiones)', 'Estimulación Cognitiva Adulto Mayor - Individual (8 sesiones)'), ('Audiologia Ocupacional', 'Audiologia Ocupacional'), ('Audiologia escolar', 'Audiologia escolar'), ('Audiologia - Limpieza de Oido', 'Audiologia - Limpieza de Oido'), ('Audiologia- lavado de oido', 'Audiologia- lavado de oido')], max_length=255, unique=True, verbose_name='Servicio terapéutico')),
                ('costo_por_sesion', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo por sesión ($)')),
                ('tipos', models.JSONField(default=list, help_text='Selecciona uno o más tipos', verbose_name='Tipo de servicio (múltiples opciones)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del servicio')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Servicio activo?')),
            ],
            options={
                'verbose_name': 'Servicio Terapéutico',
                'verbose_name_plural': 'Servicios Terapéuticos',
                'ordering': ['servicio'],
            },
        ),
    ]
