# Generated by Django 4.2.20 on 2025-05-21 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0051_servicioterapeutico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='nombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instituciones', to='usuarios.prospeccion'),
        ),
    ]
