# Generated by Django 4.2.20 on 2025-05-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0052_alter_prospecion_administrativa_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='usuarios.sucursal'),
        ),
    ]
