# Generated by Django 4.2.20 on 2025-05-21 20:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0054_alter_prospecion_administrativa_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaterapeuta',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal2', to='usuarios.sucursal'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal8', to='usuarios.sucursal'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal7', to='usuarios.sucursal'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal5', to='usuarios.sucursal'),
        ),
        migrations.AlterField(
            model_name='perfil_terapeuta',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal10', to='usuarios.sucursal'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal3', to='usuarios.sucursal'),
        ),
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal9', to='usuarios.sucursal'),
        ),
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='telefono_responsable_1',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+593', max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono responsable 1'),
        ),
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='telefono_responsable_2',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+593', max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono responsable 2'),
        ),
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='terapeutas_asignados',
            field=models.ManyToManyField(related_name='instituciones_asignadas_terapeuta', to='usuarios.perfil_terapeuta', verbose_name='Terapeutas Asignados'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal6', to='usuarios.sucursal'),
        ),
        migrations.AlterField(
            model_name='valoracionterapia',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal1', to='usuarios.sucursal'),
        ),
    ]
