# Generated by Django 4.2.20 on 2025-05-21 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0055_alter_asistenciaterapeuta_sucursal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='valorizacion_terapeutica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_terapeuticas', to='usuarios.valoracionterapia', verbose_name='Valoración Terapéutica'),
        ),
    ]
