# Generated by Django 4.2.20 on 2025-05-21 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0056_alter_profile_valorizacion_terapeutica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_terapeuticos4', to='usuarios.servicioterapeutico', verbose_name='Servicio terapéutico'),
        ),
        migrations.AlterField(
            model_name='perfil_terapeuta',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_terapeuticos1', to='usuarios.servicioterapeutico', verbose_name='Servicio terapéutico'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_terapeuticos3', to='usuarios.servicioterapeutico', verbose_name='Servicio terapéutico'),
        ),
        migrations.AlterField(
            model_name='valoracionterapia',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_terapeuticos2', to='usuarios.servicioterapeutico', verbose_name='Servicio terapéutico'),
        ),
    ]
