# Generated by Django 4.2.20 on 2025-05-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0057_alter_pagos_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='ruc',
            field=models.CharField(blank=True, help_text='Ingrese C.I del Paciente', max_length=13, null=True, verbose_name='C.I Paciente'),
        ),
    ]
