# Generated by Django 4.2.20 on 2025-05-21 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0059_alter_pagos_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='ruc',
            field=models.CharField(blank=True, help_text='Ingrese RUC de facturación', max_length=13, null=True, verbose_name='R.U.C de facturación'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unidad_educativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instituciones2', to='usuarios.prospeccion'),
        ),
    ]
