# Generated by Django 4.2.20 on 2025-05-21 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0060_alter_pagos_ruc_alter_profile_unidad_educativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='profile',
            name='sucursales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal3', to='usuarios.sucursal'),
        ),
    ]
