# Generated by Django 4.2.20 on 2025-05-21 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0061_remove_profile_sucursal_profile_sucursales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='unidad_educativa',
            new_name='institucion',
        ),
        migrations.AddField(
            model_name='profile',
            name='adjunto_autorizacion',
            field=models.FileField(blank=True, null=True, upload_to='documentos/pacientes/autorizacion/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sucursales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal33', to='usuarios.sucursal'),
        ),
    ]
