# Generated by Django 4.2.20 on 2025-05-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0062_rename_unidad_educativa_profile_institucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contrasena',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Actual contraseña de usuario'),
        ),
    ]
