# Generated by Django 4.2.20 on 2025-05-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0063_profile_contrasena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fecha_terminacion',
            new_name='fecha_alta',
        ),
        migrations.AddField(
            model_name='profile',
            name='estado_terapeutico',
            field=models.CharField(choices=[('en_terapia', 'En Terapia'), ('retirado', 'Retirado'), ('alta', 'Alta'), ('pausa', 'Pausa')], default='en_terapia', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_pausa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='motivo_otro',
            field=models.CharField(blank=True, help_text='Especifique otro motivo (si aplica)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='motivo_retiro',
            field=models.CharField(blank=True, choices=[('economico', 'Económico'), ('insatisfecho', 'Insatisfecho'), ('otro', 'Otro')], max_length=50, null=True),
        ),
    ]
