# Generated by Django 4.2.20 on 2025-05-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0064_rename_fecha_terminacion_profile_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacoradesarrollo',
            options={'ordering': ['-fecha'], 'verbose_name': 'Entrada de Bitácora', 'verbose_name_plural': 'Bitácora de Desarrollo QND.0.3.0.2'},
        ),
        migrations.AddField(
            model_name='bitacoradesarrollo',
            name='minutos_empleados',
            field=models.PositiveIntegerField(default=0, verbose_name='Minutos Empleados'),
        ),
        migrations.AddField(
            model_name='bitacoradesarrollo',
            name='minutos_restantes',
            field=models.PositiveIntegerField(default=4320, editable=False, verbose_name='Minutos Restantes'),
        ),
    ]
