# Generated by Django 4.2.20 on 2025-05-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0065_alter_bitacoradesarrollo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_terapeuta',
            name='tipo_servicio',
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='tipo_servicio',
            field=models.ManyToManyField(blank=True, related_name='servicios_terapeuticos1', to='usuarios.servicioterapeutico', verbose_name='Servicio terapéutico'),
        ),
    ]
