# Generated by Django 4.2.20 on 2025-05-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0066_remove_perfil_terapeuta_tipo_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fecha_re_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de re inicio de tratamiento'),
        ),
    ]
