# Generated by Django 4.2.20 on 2025-05-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0067_profile_fecha_re_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certificado_final',
            field=models.FileField(blank=True, null=True, upload_to='certificados/final/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='certificado_inicio',
            field=models.FileField(blank=True, null=True, upload_to='certificados/inicio/'),
        ),
    ]
