# Generated by Django 4.2.20 on 2025-05-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0069_cita_profile_terapeuta_alter_cita_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='tipo_cita',
            field=models.CharField(choices=[('administrativa', 'Administrativa'), ('terapeutica', 'Terapéutica'), ('particular', 'Particular'), ('urgente', 'Urgente')], default='terapeutica', max_length=20, verbose_name='Categoria de Cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Confirmada'),
        ),
    ]
