# Generated by Django 4.2.20 on 2025-05-22 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0070_cita_tipo_cita_alter_cita_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaterapeuta',
            name='evento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.cita', verbose_name='Cita Agendada'),
        ),
    ]
