# Generated by Django 4.2.20 on 2025-05-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0071_alter_asistenciaterapeuta_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Confirmada por el paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Cancelada por el paciente'),
        ),
    ]
