# Generated by Django 4.2.20 on 2025-05-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0073_alter_cita_creador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha'], 'verbose_name': 'Cita Agendada', 'verbose_name_plural': 'Citas Agendadas'},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'ordering': ['fecha_emision_factura'], 'verbose_name': 'Orden de Pago ', 'verbose_name_plural': 'Ordenes de Pago'},
        ),
        migrations.AlterModelOptions(
            name='tareacomentario',
            options={'ordering': ['fecha'], 'verbose_name': 'Revisar Tarea Terapeutica', 'verbose_name_plural': 'Revisar Tareas Terapeuticas'},
        ),
        migrations.AlterModelOptions(
            name='tareas',
            options={'ordering': ['paciente'], 'verbose_name': 'Paciente/ Tareas', 'verbose_name_plural': 'Tareas Asignadas'},
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Terapeuta activo?'),
        ),
    ]
