# Generated by Django 4.2.20 on 2025-05-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0074_alter_cita_options_alter_pagos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospecion_administrativa',
            name='estado',
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='es_capacitacion',
            field=models.BooleanField(default=False, verbose_name='¿Recibió capacitación?'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='es_contactado',
            field=models.BooleanField(default=False, verbose_name='¿Ya fue contactado?'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='es_convenio_firmado',
            field=models.BooleanField(default=False, verbose_name='¿Firmó convenio?'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='es_en_cita',
            field=models.BooleanField(default=False, verbose_name='¿Ya tuvo cita?'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='es_en_terapia',
            field=models.BooleanField(default=False, verbose_name='¿Recibe terapia?'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='es_finalizado',
            field=models.BooleanField(default=False, verbose_name='¿Finalizó el proceso?'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='es_inactivo',
            field=models.BooleanField(default=False, verbose_name='¿Está inactivo?'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='es_por_contactar',
            field=models.BooleanField(default=False, verbose_name='¿Se intentó contactar?'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='es_rechazado',
            field=models.BooleanField(default=False, verbose_name='¿Fue rechazado?'),
        ),
        migrations.AddField(
            model_name='prospecion_administrativa',
            name='es_valoracion',
            field=models.BooleanField(default=False, verbose_name='¿Tuvo valoración?'),
        ),
    ]
