# Generated by Django 4.2.20 on 2025-05-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0075_remove_prospecion_administrativa_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='estado_terapeutico',
        ),
        migrations.AddField(
            model_name='profile',
            name='es_alta',
            field=models.BooleanField(default=False, verbose_name='¿Tiene alta terapéutica?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='es_en_terapia',
            field=models.BooleanField(default=False, verbose_name='¿Ha estado en terapia?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='es_pausa',
            field=models.BooleanField(default=False, verbose_name='¿Ha estado en pausa?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='es_retirado',
            field=models.BooleanField(default=False, verbose_name='¿Ha sido retirado?'),
        ),
    ]
