# Generated by Django 4.2.20 on 2025-05-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0076_remove_profile_estado_terapeutico_profile_es_alta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='cita',
            name='cancelada',
            field=models.BooleanField(default=False, verbose_name='¿Cancelada?'),
        ),
        migrations.AddField(
            model_name='cita',
            name='confirmada',
            field=models.BooleanField(default=False, verbose_name='¿Confirmada?'),
        ),
        migrations.AddField(
            model_name='cita',
            name='pendiente',
            field=models.BooleanField(default=True, verbose_name='¿Pendiente?'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo_cita',
            field=models.CharField(choices=[('administrativa', 'Administrativa'), ('terapeutica', 'Terapéutica'), ('particular', 'Particular'), ('urgente', 'Urgente')], default='terapeutica', max_length=20, verbose_name='Categoría de Cita'),
        ),
    ]
