# Generated by Django 4.2.20 on 2025-05-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0077_remove_cita_estado_remove_cita_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='al_dia',
            field=models.BooleanField(default=False, verbose_name='Pago al día'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='pendiente',
            field=models.BooleanField(default=False, verbose_name='Pago pendiente'),
        ),
        migrations.AddField(
            model_name='pagos',
            name='vencido',
            field=models.BooleanField(default=False, verbose_name='Pago vencido'),
        ),
    ]
