# Generated by Django 4.2.20 on 2025-05-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0078_pagos_al_dia_pagos_pendiente_pagos_vencido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracionterapia',
            name='tipo_valoracion',
        ),
        migrations.AddField(
            model_name='valoracionterapia',
            name='es_convenio',
            field=models.BooleanField(default=False, verbose_name='Valoración por Convenio'),
        ),
        migrations.AddField(
            model_name='valoracionterapia',
            name='es_particular',
            field=models.BooleanField(default=False, verbose_name='Valoración Particular'),
        ),
    ]
