# Generated by Django 4.2.20 on 2025-05-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0079_remove_valoracionterapia_tipo_valoracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='tarea_no_realizada',
            field=models.BooleanField(default=False, verbose_name='¿Paciente no la ha realizado?'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='realizada',
            field=models.BooleanField(default=False, verbose_name='¿Paciente realizó la tarea?'),
        ),
    ]
