# Generated by Django 4.2.20 on 2025-05-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0080_tareas_tarea_no_realizada_alter_tareas_realizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciaterapeuta',
            name='asistire',
            field=models.BooleanField(default=False, verbose_name='¿Confirmo que asistiré?'),
        ),
        migrations.AddField(
            model_name='asistenciaterapeuta',
            name='no_asistire',
            field=models.BooleanField(default=False, verbose_name='¿Confirmo que no asistiré?'),
        ),
    ]
