# Generated by Django 4.2.20 on 2025-05-29 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0081_asistenciaterapeuta_asistire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_terapeuta',
            name='datos_bancarios',
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='banco',
            field=models.CharField(blank=True, choices=[('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('pacifico', 'Banco del Pacífico'), ('produbanco', 'Produbanco'), ('internacional', 'Banco Internacional'), ('austro', 'Banco del Austro'), ('machala', 'Banco de Machala'), ('bolivariano', 'Banco Bolivariano'), ('promerica', 'Banco Promerica'), ('coopjep', 'Cooperativa JEP'), ('cooperco', 'Cooperco'), ('mutualista_pichincha', 'Mutualista Pichincha'), ('', 'Otro')], help_text='Selecciona el banco', max_length=50, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de cuenta'),
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente')], max_length=20, null=True, verbose_name='Tipo de cuenta'),
        ),
        migrations.AlterField(
            model_name='perfil_terapeuta',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Elegir nombre de usuario en el sistema'),
        ),
    ]
