# Generated by Django 4.2.20 on 2025-05-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0082_remove_perfil_terapeuta_datos_bancarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
