# Generated by Django 4.2.20 on 2025-05-29 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0083_perfil_terapeuta_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de Usuario'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.profile', verbose_name='Paciente'),
        ),
    ]
