# Generated by Django 4.2.20 on 2025-05-29 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0084_alter_pagos_cliente_alter_pagos_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionterapia',
            name='perfil_terapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_terapeuta_asignado', to=settings.AUTH_USER_MODEL),
        ),
    ]
