# Generated by Django 4.2.20 on 2025-05-29 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0086_alter_valoracionterapia_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='terapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terapeuta_asiga_tarea', to=settings.AUTH_USER_MODEL),
        ),
    ]
