# Generated by Django 4.2.20 on 2025-05-29 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0087_alter_tareas_terapeuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Elija el nombre de usuario del paciente'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='tarea_no_realizada',
            field=models.BooleanField(default=False, verbose_name='¿Paciente Culminó la Terapia ?'),
        ),
    ]
