# Generated by Django 4.2.20 on 2025-05-29 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0089_tareas_cita_terapeutica_asignada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaterapeuta',
            name='terapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencia_terapeutica', to=settings.AUTH_USER_MODEL),
        ),
    ]
