# Generated by Django 4.2.20 on 2025-06-02 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0090_alter_asistenciaterapeuta_terapeuta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Notificaciones de  MEDDES®', 'verbose_name_plural': 'Bandeja de entrada MEDDES®'},
        ),
        migrations.RemoveField(
            model_name='perfil_terapeuta',
            name='edad',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario'),
        ),
    ]
