# Generated by Django 4.2.20 on 2025-06-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0091_alter_mensaje_options_remove_perfil_terapeuta_edad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='edad',
        ),
    ]
