# Generated by Django 4.2.20 on 2025-06-02 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0093_alter_profile_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareas',
            options={'ordering': ['profile__user__first_name'], 'verbose_name': 'Paciente/ Tareas', 'verbose_name_plural': 'Tareas Asignadas'},
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='paciente',
        ),
        migrations.AlterField(
            model_name='cita',
            name='cancelada',
            field=models.BooleanField(default=False, verbose_name='Cancelada'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='confirmada',
            field=models.BooleanField(default=False, verbose_name='Confirmada'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Cita con:'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='pendiente',
            field=models.BooleanField(default=True, verbose_name='Pendiente'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='es_alta',
            field=models.BooleanField(default=False, verbose_name='En Alta'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='es_en_terapia',
            field=models.BooleanField(default=False, verbose_name='En terapia'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='es_pausa',
            field=models.BooleanField(default=False, verbose_name='En Pausa'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='es_retirado',
            field=models.BooleanField(default=False, verbose_name='Retirado'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Alta'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Asignar_perfil_de_paciente2', to='usuarios.profile', verbose_name='Asignar perfil de paciente'),
        ),
    ]
