# Generated by Django 4.2.20 on 2025-06-03 11:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0094_alter_tareas_options_remove_tareas_paciente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistenciaterapeuta',
            options={'ordering': ['-evento']},
        ),
        migrations.AlterUniqueTogether(
            name='asistenciaterapeuta',
            unique_together={('terapeuta', 'hora_salida')},
        ),
        migrations.RemoveField(
            model_name='asistenciaterapeuta',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='asistenciaterapeuta',
            name='hora_entrada',
        ),
    ]
