# Generated by Django 4.2.20 on 2025-06-03 13:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0097_alter_asistenciaterapeuta_terapeuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='cuerpo',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Cuerpo del mensaje'),
        ),
    ]
