# Generated by Django 4.2.20 on 2025-06-03 13:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0099_alter_asistenciaterapeuta_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareacomentario',
            name='mensaje',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Comentario o actividad a realizar'),
        ),
    ]
