# Generated by Django 4.2.20 on 2025-06-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0101_administrativeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeprofile',
            name='department',
            field=models.CharField(choices=[('gerencia', 'Gerencia'), ('administracion', 'Administración'), ('financiero', 'Financiero')], max_length=30, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='administrativeprofile',
            name='job_title',
            field=models.CharField(choices=[('gerente_general', 'Gerente General'), ('gerente_comercial', 'Gerente Comercial'), ('tecnico_administrativo', 'Técnico Administrativo'), ('asistente_administrativo', 'Asistente Administrativo'), ('contador', 'Contador'), ('analista_financiero', 'Analista Financiero'), ('jefe_finanzas', 'Jefe de Finanzas')], max_length=50, verbose_name='Cargo'),
        ),
    ]
