# Generated by Django 4.2.20 on 2025-06-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0103_administrativeprofile_num_pacientes_captados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeprofile',
            name='address',
            field=models.CharField(max_length=200, unique=True, verbose_name='Direccion de Domicilio'),
        ),
    ]
