# Generated by Django 4.2.20 on 2025-06-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0104_alter_administrativeprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeprofile',
            name='national_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cédula de identidad'),
        ),
    ]
