# Generated by Django 4.2.20 on 2025-06-05 19:15

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0105_alter_administrativeprofile_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='tipos',
            field=models.JSONField(default=list, help_text='Selecciona uno o más tipos', verbose_name='Tipo de servicio (múltiples opciones)'),
        ),
        migrations.AlterField(
            model_name='administrativeprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+593', max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfono de la Institución'),
        ),
    ]
