# Generated by Django 4.2.20 on 2025-06-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0106_perfil_terapeuta_tipos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_terapeuta',
            name='tipo_servicio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tipo_servicio',
        ),
        migrations.AddField(
            model_name='profile',
            name='tipos',
            field=models.JSONField(default=list, help_text='Selecciona uno o más tipos', verbose_name='Tipo de servicio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='certificado_inicio',
            field=models.FileField(blank=True, null=True, upload_to='certificados/inicio/', verbose_name='Autorización Terapéutica'),
        ),
    ]
