# Generated by Django 4.2.20 on 2025-06-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0107_remove_perfil_terapeuta_tipo_servicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_terapeuta',
        ),
        migrations.AddField(
            model_name='perfil_terapeuta',
            name='servicio_consulta',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_terapeutas',
            field=models.ManyToManyField(blank=True, related_name='asignaciones', to='usuarios.perfil_terapeuta', verbose_name='Elegir Terapéutas Asignados'),
        ),
    ]
