# Generated by Django 4.2.20 on 2025-06-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0108_remove_profile_user_terapeuta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='informe_inicial',
            field=models.FileField(blank=True, null=True, upload_to='informes/inicio/', verbose_name='Informe Terapéutico Inicial'),
        ),
        migrations.AddField(
            model_name='profile',
            name='informe_segimiento',
            field=models.FileField(blank=True, null=True, upload_to='informes/seguimiento3M/', verbose_name='Informe de seguimiento Terapéutico 3 meses'),
        ),
        migrations.AddField(
            model_name='profile',
            name='informe_segimiento_2',
            field=models.FileField(blank=True, null=True, upload_to='informes/seguimiento6M/', verbose_name='Informe de seguimiento Terapéutico 6 meses'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='certificado_inicio',
            field=models.FileField(blank=True, null=True, upload_to='certificados/inicio/', verbose_name='Autorización inicio Terapéutico'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipos',
            field=models.JSONField(default=list, help_text='Selecciona uno o más tipos', verbose_name='servicios contratados'),
        ),
    ]
