# Generated by Django 4.2.20 on 2025-06-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0109_profile_informe_inicial_profile_informe_segimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagos',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orden de Pago ', 'verbose_name_plural': 'Ordenes de Pago'},
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='colegio',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='comprobante_pago',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='estado_de_pago',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='fecha_emision_factura',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='numero_de_comprobante',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='servicio',
        ),
        migrations.AddField(
            model_name='pagos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha en que se creó el registro de pago', null=True, verbose_name='Fecha de creación'),
        ),
    ]
