# Generated by Django 4.2.20 on 2025-06-06 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0110_alter_pagos_options_remove_pagos_banco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='convenio',
        ),
        migrations.AlterField(
            model_name='pagos',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucursal4', to='usuarios.sucursal'),
        ),
    ]
