# Generated by Django 4.2.20 on 2025-06-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0112_perfil_terapeuta_pago_por_hora_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeprofile',
            name='department',
            field=models.CharField(choices=[('gerencia', 'Gerencia'), ('administracion', 'Administración'), ('financiero', 'Financiero'), ('operativo', 'Operativo')], max_length=30, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='administrativeprofile',
            name='job_title',
            field=models.CharField(choices=[('gerente_general', 'Gerente General'), ('gerente_comercial', 'Ejecutivo Comercial'), ('tecnico_administrativo', 'Técnico Administrativo'), ('asistente_administrativo', 'Asistente Administrativo'), ('terapeuta', 'Terapéuta'), ('contador', 'Contador'), ('analista_financiero', 'Analista Financiero'), ('jefe_finanzas', 'Jefe de Finanzas')], max_length=50, verbose_name='Cargo'),
        ),
    ]
