# Generated by Django 4.2.20 on 2025-06-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0113_alter_administrativeprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracionterapia',
            name='institucion_sin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de institución sin convenio'),
        ),
        migrations.AddField(
            model_name='valoracionterapia',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='valoracionterapia',
            name='numero_dece',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numero de DECE'),
        ),
    ]
