# Generated by Django 4.2.20 on 2025-06-06 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0004_servicioterapeutico_antecedentes_penales_and_more'),
        ('usuarios', '0114_valoracionterapia_institucion_sin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionterapia',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_terapeutico', to='serviceapp.servicioterapeutico', verbose_name='Servicio terapéutico'),
        ),
        migrations.DeleteModel(
            name='ServicioTerapeutico',
        ),
    ]
