# Generated by Django 4.2.20 on 2025-06-06 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0115_alter_valoracionterapia_servicio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospeccion',
            options={'ordering': ['-fecha_contacto'], 'verbose_name': 'Administrativo / Prospecciones', 'verbose_name_plural': 'Registros Administrativos / Prospección '},
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='psicologia_email',
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='psicologia_fecha_proximo_contacto',
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='psicologia_observaciones',
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='sostenimiento',
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='tl_cargo_contacto',
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='tl_email',
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='tl_fecha_contacto',
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='tl_fecha_proximo_contacto',
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='tl_nombre_contacto',
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='tl_observaciones',
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='tl_proceso_realizado',
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='tl_responsable',
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='vya_fecha_proximo_contacto',
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='vya_observacion',
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='vya_observaciones',
        ),
        migrations.RemoveField(
            model_name='prospeccion',
            name='zona',
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='cargo_contacto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo del Contacto'),
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto'),
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='fecha_contacto',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Contacto'),
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='fecha_proximo_contacto',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Próximo Contacto'),
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de Contacto'),
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='proceso_realizado',
            field=models.TextField(blank=True, null=True, verbose_name='Proceso Realizado'),
        ),
        migrations.AddField(
            model_name='prospeccion',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable del contacto'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='nombre_institucion',
            field=models.CharField(max_length=255, verbose_name='Nombre de la Institución'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='provincia',
            field=models.CharField(max_length=100, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
