# Generated by Django 4.2.20 on 2025-06-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0116_alter_prospeccion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospeccion',
            name='direccion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='email_contacto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email de Contacto'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='fecha_contacto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fecha de Contacto'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='fecha_proximo_contacto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fecha Próximo Contacto'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='proceso_realizado',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Proceso Realizado'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='responsable',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsable del contacto'),
        ),
        migrations.AlterField(
            model_name='prospeccion',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
