# Generated by Django 4.2.20 on 2025-06-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0117_alter_prospeccion_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospeccion',
            name='estado',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
    ]
