# Generated by Django 4.2.20 on 2025-06-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0118_alter_prospeccion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
