# Generated by Django 4.2.20 on 2025-06-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0119_alter_prospecion_administrativa_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('Ambato', 'Ambato'), ('Arenillas', 'Arenillas'), ('Atacames', 'Atacames'), ('Atuntaqui', 'Atuntaqui'), ('Azogues', 'Azogues'), ('Babahoyo', 'Babahoyo'), ('Bahía de Caráquez', 'Bahía de Caráquez'), ('Balzar', 'Balzar'), ('Baños de Agua Santa', 'Baños de Agua Santa'), ('Buena Fé', 'Buena Fé'), ('Calceta', 'Calceta'), ('Cañar', 'Cañar'), ('Cariamanga', 'Cariamanga'), ('Catamayo', 'Catamayo'), ('Cayambe', 'Cayambe'), ('Chone', 'Chone'), ('Cuenca', 'Cuenca'), ('Daule', 'Daule'), ('Durán', 'Durán'), ('El Carmen', 'El Carmen'), ('El Guabo', 'El Guabo'), ('El Triunfo', 'El Triunfo'), ('Esmeraldas', 'Esmeraldas'), ('Gualaceo', 'Gualaceo'), ('Guaranda', 'Guaranda'), ('Guayaquil', 'Guayaquil'), ('Huaquillas', 'Huaquillas'), ('Ibarra', 'Ibarra'), ('Jaramijó', 'Jaramijó'), ('Jipijapa', 'Jipijapa'), ('La Concordia', 'La Concordia'), ('La Libertad', 'La Libertad'), ('La Maná', 'La Maná'), ('Latacunga', 'Latacunga'), ('La Troncal', 'La Troncal'), ('Loja', 'Loja'), ('Lomas de Sargentillo', 'Lomas de Sargentillo'), ('Macará', 'Macará'), ('Macas', 'Macas'), ('Machachi', 'Machachi'), ('Machala', 'Machala'), ('Manta', 'Manta'), ('Milagro', 'Milagro'), ('Montalvo', 'Montalvo'), ('Montecristi', 'Montecristi'), ('Naranjal', 'Naranjal'), ('Naranjito', 'Naranjito'), ('Nueva Loja', 'Nueva Loja'), ('Otavalo', 'Otavalo'), ('Pasaje', 'Pasaje'), ('Pedernales', 'Pedernales'), ('Pedro Carbo', 'Pedro Carbo'), ('Piñas', 'Piñas'), ('Playas', 'Playas'), ('Portoviejo', 'Portoviejo'), ('Puerto Baquerizo Moreno', 'Puerto Baquerizo Moreno'), ('Puerto Francisco de Orellana', 'Puerto Francisco de Orellana'), ('Puyo', 'Puyo'), ('Quevedo', 'Quevedo'), ('Quito', 'Quito'), ('Riobamba', 'Riobamba'), ('Rosa Zárate', 'Rosa Zárate'), ('Salcedo', 'Salcedo'), ('Salinas', 'Salinas'), ('Samborondón', 'Samborondón'), ('San Gabriel', 'San Gabriel'), ('Sangolquí', 'Sangolquí'), ('San Lorenzo', 'San Lorenzo'), ('Santa Elena', 'Santa Elena'), ('Santa Rosa', 'Santa Rosa'), ('Santo Domingo de los Colorados', 'Santo Domingo de los Colorados'), ('Shushufindi', 'Shushufindi'), ('Tena', 'Tena'), ('Tulcán', 'Tulcán'), ('Valencia', 'Valencia'), ('Velasco Ibarra', 'Velasco Ibarra'), ('Ventanas', 'Ventanas'), ('Vinces', 'Vinces'), ('Yaguachi', 'Yaguachi'), ('Zamora', 'Zamora')], default='Quito', max_length=100, null=True),
        ),
    ]
