# Generated by Django 4.2.20 on 2025-06-10 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0120_alter_prospecion_administrativa_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prospecion_administrativa',
            name='ejecutivo_meddes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.administrativeprofile', verbose_name='Ejecutivo Meddes'),
        ),
    ]
