# Generated by Django 4.2.20 on 2025-06-10 17:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0121_alter_prospecion_administrativa_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='notas',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Notas adicionales'),
        ),
    ]
