# Generated by Django 4.2.20 on 2025-06-10 17:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0122_alter_cita_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionterapia',
            name='observaciones',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Notas adicionales'),
        ),
    ]
