# Generated by Django 4.2.20 on 2025-06-10 17:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0123_alter_valoracionterapia_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionterapia',
            name='diagnostico',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='descripción del diagnóstico'),
        ),
        migrations.AlterField(
            model_name='valoracionterapia',
            name='observaciones',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='observaciones de la valoración'),
        ),
    ]
