# Generated by Django 4.2.20 on 2025-06-11 18:31

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0124_alter_valoracionterapia_diagnostico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='fecha_final',
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de la cita'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='descripcion_tarea',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Describa la tarea a realizar'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='media_terapia',
            field=models.FileField(blank=True, upload_to='Videos/%Y/%m/%d/', verbose_name='Contenido Multimedia '),
        ),
    ]
