# Generated by Django 4.2.20 on 2025-06-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0125_remove_cita_fecha_final_alter_cita_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de la cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas adicionales'),
        ),
    ]
