# Generated by Django 4.2.20 on 2025-06-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0005_remove_servicioterapeutico_antecedentes_penales_and_more'),
        ('usuarios', '0126_cita_hora_alter_cita_fecha_alter_cita_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_terapeutico', to='serviceapp.servicioterapeutico', verbose_name='Servicio terapéutico'),
        ),
        migrations.AlterField(
            model_name='valoracionterapia',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_terapeutico_pagos', to='serviceapp.servicioterapeutico', verbose_name='Servicio terapéutico'),
        ),
    ]
