# Generated by Django 4.2.20 on 2025-07-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0129_pagos_comprobante_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=10, null=True),
        ),
    ]
