# Generated by Django 4.2.20 on 2025-07-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0130_cita_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='nombre_paciente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Paciente Parciular'),
        ),
    ]
