# Generated by Django 4.2.20 on 2025-07-01 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0131_cita_nombre_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='dia_semana',
        ),
        migrations.AlterField(
            model_name='cita',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_recibidas', to=settings.AUTH_USER_MODEL, verbose_name=' Asignar cita a Administrativo'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nombre_paciente',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Paciente Particular'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Asignar_perfil_de_paciente', to='usuarios.profile', verbose_name='Asignar cita a paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='profile_terapeuta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Asignar_perfil_de_terapeuta', to='usuarios.perfil_terapeuta', verbose_name='Asignar cita a terapeuta'),
        ),
    ]
