# Generated by Django 4.2.20 on 2025-06-05 14:20

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_servicioterapeutico_costo_por_sesion_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioterapeutico',
            name='costo_por_sesion',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=10, null=True, verbose_name='Valor por sesión'),
        ),
    ]
