# Generated by Django 4.2.20 on 2025-06-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_alter_servicioterapeutico_costo_por_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioterapeutico',
            name='antecedentes_penales',
            field=models.FileField(blank=True, null=True, upload_to='documentos/terapeutas/antecedentes/'),
        ),
        migrations.AddField(
            model_name='servicioterapeutico',
            name='certificados',
            field=models.FileField(blank=True, null=True, upload_to='documentos/terapeutas/certificados/'),
        ),
        migrations.AddField(
            model_name='servicioterapeutico',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicioterapeutico',
            name='titulo_universitario',
            field=models.FileField(blank=True, null=True, upload_to='documentos/terapeutas/titulo/'),
        ),
    ]
