# Generated by Django 4.2.20 on 2025-06-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0004_servicioterapeutico_antecedentes_penales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicioterapeutico',
            name='antecedentes_penales',
        ),
        migrations.RemoveField(
            model_name='servicioterapeutico',
            name='certificados',
        ),
        migrations.RemoveField(
            model_name='servicioterapeutico',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='servicioterapeutico',
            name='titulo_universitario',
        ),
        migrations.AlterField(
            model_name='servicioterapeutico',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Escriba Detalle del servicio'),
        ),
    ]
