# Generated by Django 4.2.20 on 2025-06-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0005_remove_servicioterapeutico_antecedentes_penales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioterapeutico',
            name='servicio',
            field=models.CharField(choices=[('TERAPIA DE LENGUAJE', 'Terapia de Lenguaje'), ('ESTIMULACIÓN COGNITIVA', 'Estimulación Cognitiva'), ('PSICOLOGÍA', 'Psicología'), ('ESTIMULACIÓN TEMPRANA', 'Estimulación Temprana'), ('VALORACIÓN', 'Valoración')], max_length=255, verbose_name='Servicio terapéutico'),
        ),
    ]
