# Generated by Django 4.2.20 on 2025-07-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0006_alter_servicioterapeutico_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioterapeutico',
            name='servicio',
            field=models.CharField(choices=[('TERAPIA_DE_LENGUAJE', 'Terapia de Lenguaje'), ('ESTIMULACION_COGNITIVA', 'Estimulación Cognitiva'), ('TERAPIA_OCUPACIONAL', 'Terapia Ocupacional'), ('PSICOLOGIA_PAREJA', 'Psicología - Pareja'), ('PSICOLOGIA_INFANTIL', 'Psicología - Infantil'), ('PSICOLOGIA_FAMILIAR', 'Psicología - Familiar'), ('PSICOLOGIA_ADULTOS', 'Psicología - Adultos'), ('VALORACION_PSICOLOGICA', 'Valoración Psicológica'), ('VALORACION_LENGUAJE', 'Valoración de Lenguaje'), ('ESTIMULACION_TEMPRANA', 'Estimulación Temprana'), ('AUDIOLOGIA', 'Audiología'), ('OPTOMETRIA_OFTALMOLOGIA', 'Optometría / Oftalmología')], max_length=255, verbose_name='Servicio terapéutico'),
        ),
    ]
