# Generated by Django 4.2.20 on 2025-07-02 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('fecha_final', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True, null=True)),
                ('sucursal', models.CharField(blank=True, choices=[('Quito - Valles', 'Quito - Valles'), ('Quito - Centro', 'Quito - Centro'), ('Guayaquil', 'Guayaquil'), ('Manta', 'Manta')], max_length=255, null=True, verbose_name='Sucursal')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crear_citas', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibir_citas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrativos / Ingreso de Cita',
                'verbose_name_plural': 'Registros Administrativos / Ingreso de Citas',
                'ordering': ['-fecha'],
            },
        ),
    ]
